main_list: main.c BSTreeList.c BSTreeList.h
	gcc -DUSE_LIST -o main_list main.c BSTreeList.c

main_node: main.c BSTreeNode.c BSTreeNode.h
	gcc -o main_node main.c BSTreeNode.c

main_avl: AVLTree.c
	gcc AVLTree.c -o main_avl